apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: <NAMESPACE>
spec:
  selector:
    matchLabels:
      app: <APP_NAME>
  replicas: 1
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - name: <CONTAINER_NAME>
          image: <IMAGE_NAME>
          ports:
            - containerPort: <PORT>

---
apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>
  namespace: <NAMESPACE>
spec:
  type: NodePort
  selector:
    app: <APP_NAME>
  ports:
    - port: <PORT>
      targetPort: <PORT>

