name: Deployment-service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: medyagh/setup-minikube@latest
    - name: Check deployments
      run: kubectl get deployments -A
    - name: Check Service
      run: kubectl get services -A


    
