name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Service
      run: kubectl get services -A
    - name: minikube service url
      run: minikube service nginx-service --url
