name: Building and pushing docker image

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select an Tag name for image
        
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.USER_NAME }}
       password: ${{ secrets.ACCESS_TOKEN }}

    - name: Build and push dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ravinder4u/new-xenonn-image:${{ github.sha}}
