name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: minikube start
      run: minikube status
    - name: Check Service
      run: kubectl get pods -A
    - name: minikube service url
      run: minikube service nginx-service --url
