name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: minikube start
      run: minikube start
    - name: minikube status
      run: minikube status
    - name: Check Service
      run: |
           kubectl get pods -A
           sleep 60
    - name: Check pod health
      run: kubectl get pods -A
   
