name: Building and pushing Docker image

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Please enter Dockerhub Username"
        required: true
      imagename:
        description: "Please enter your Image name"
        required: true
      tagname:
        description: "Please enter tagname for image"
        required: true
      appname:
        description: "Enter the app name"
        required: true
      containername:
        description: "Enter the name of the container"
        required: true
      portvalue:
        description: "Enter the value of port"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ inputs.username }}/${{ inputs.imagename }}:${{ inputs.tagname }}

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: 'latest'
        driver: 'docker'

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        kubectl config use-context minikube
        IMAGE_NAME="${{ inputs.username }}/${{ inputs.imagename }}:${{ inputs.tagname }}"
        APP_NAME="${{ inputs.appname }}"
        PORT="${{ inputs.portvalue }}"
        CONTAINER_NAME="${{ inputs.containername }}"
        sed "s|<IMAGE_NAME>|${IMAGE_NAME}|g; s|<APP_NAME>|${APP_NAME}|g; s|<PORT>|${PORT}|g; s|<CONTAINER_NAME>|${CONTAINER_NAME}|g" deploy.template.yml > deploy-new.yml 

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deploy-new.yml
        sleep 60  
        kubectl get pods
        kubectl get services
        MINIKUBE_URL= $(minikube get "${{ inputs.appname }} --url)
        curl $MINIKUBE_URL
   
