name: Setup YQ on Push

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  setup-yq:
    runs-on: self-hosted

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Check YQ Version
      run: |
        yq --version

